CREATE DATABASE amm;
\C amm
CREATE TABLE users (id SERIAL PRIMARY KEY,username VARCHAR(50) NOT NULL,password VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL, auth VARCHAR(300));
CREATE TABLE ardu(text VARCHAR(500));
