CREATE DATABASE amm;
CREATE TABLE users (id SERIAL PRIMARY KEY,username VARCHAR(50) NOT NULL,password VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL, auth VARCHAR(300));
CREATE TABLE project (id SERIAL PRIMARY KEY,userid INT NOT NULL,plan VARCHAR(500) NOT NULL, date VARCHAR(50) NOT NULL);
